# Generated by Django 2.0.4 on 2018-05-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Network', '0004_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='To',
            field=models.CharField(max_length=50),
        ),
    ]
