# Generated by Django 2.0.4 on 2018-05-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Network', '0006_auto_20180503_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='To',
        ),
    ]
