# Generated by Django 2.0.4 on 2018-05-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Network', '0008_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='interaction',
            field=models.IntegerField(blank=True),
        ),
    ]
