# Generated by Django 2.0.4 on 2018-05-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Network', '0009_auto_20180505_1816'),
        ('Social_Network', '0009_auto_20180503_2119'),
    ]

    operations = [
    ]
